name: professional_reset_api
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  dio: ^5.3.3
  dio_cookie_manager: ^2.0.0
  cookie_jar: ^3.0.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  freezed: ^2.4.5
  get_it: ^7.6.4
  json_annotation: ^4.8.1
  retrofit: ^4.0.3
  logger: any
  meta: ^1.9.1

dev_dependencies:
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  retrofit_generator: ^8.0.1

  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
