name: professional_reset_api
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  cookie_jar: ^3.0.1
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  # dio_cookie_manager: ^2.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  freezed: ^2.1.0+1
  freezed_annotation: ^2.1.0
  get_it: ^7.6.4
  json_annotation: ^4.8.1
  logger: any
  meta: ^1.9.1
  retrofit: ^3.0.1+1

dev_dependencies:
  build_runner: ^2.4.6
  flutter_lints: ^2.0.0

  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.1
  retrofit_generator: ^4.0.3

flutter:

  uses-material-design: true
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
